// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTj0KURGfXfJ6MwOd6EBiXbpuhB3C7G0w',
    appId: '1:45542029744:web:543fef2f5236aff7f73e75',
    messagingSenderId: '45542029744',
    projectId: 'dinetrack-d2b14',
    authDomain: 'dinetrack-d2b14.firebaseapp.com',
    storageBucket: 'dinetrack-d2b14.firebasestorage.app',
    measurementId: 'G-8ZYC9FKXM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABSpDF1wKaFsNjp_2fMZrVgPDEZA-xFtM',
    appId: '1:45542029744:android:08ee84eb6e9c1bf7f73e75',
    messagingSenderId: '45542029744',
    projectId: 'dinetrack-d2b14',
    storageBucket: 'dinetrack-d2b14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh1wxPVta-YPS-SvmnDf4KC8Uc_MfHJeY',
    appId: '1:45542029744:ios:96f4f0c142acbbf3f73e75',
    messagingSenderId: '45542029744',
    projectId: 'dinetrack-d2b14',
    storageBucket: 'dinetrack-d2b14.firebasestorage.app',
    iosBundleId: 'com.example.dinetrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh1wxPVta-YPS-SvmnDf4KC8Uc_MfHJeY',
    appId: '1:45542029744:ios:96f4f0c142acbbf3f73e75',
    messagingSenderId: '45542029744',
    projectId: 'dinetrack-d2b14',
    storageBucket: 'dinetrack-d2b14.firebasestorage.app',
    iosBundleId: 'com.example.dinetrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTj0KURGfXfJ6MwOd6EBiXbpuhB3C7G0w',
    appId: '1:45542029744:web:2d02f92df4488a4ef73e75',
    messagingSenderId: '45542029744',
    projectId: 'dinetrack-d2b14',
    authDomain: 'dinetrack-d2b14.firebaseapp.com',
    storageBucket: 'dinetrack-d2b14.firebasestorage.app',
    measurementId: 'G-JS2N3M0CCP',
  );
}
